### ISSUE TITLE
Naming & versioning for Srophé forks

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe#10]
@wsalesky Is there a standard now for Srophé forks regarding naming, URI, and versioning?
E.g., https://github.com/usaybia/srophe/commit/d3d42270ed032257b2babc0f5e3bafee046649a5

**Comment by wsalesky** [comment]
There has not been, but we should adopt one. I have been changing the
naming and URIs so I can run all the versions locally on the same eXist-db
instance, but I have not standardized anything. I'm happy to work with you
on that.

**Comment by nathangibson** [comment]
@wsalesky Thanks. What do you think of 
```
<package xmlns="http://expath.org/ns/pkg" name="http://srophe.org/usaybia" abbrev="usaybia" version="0.9.0-dev" spec="1.0">
    <title>Usaybia.net</title>
    <dependency package="http://exist-db.org/apps/shared"/>
</package>
```

**Naming:** Is there somewhere here we should more clearly show that this is a fork of Srophé? Does the `http://srophe.org/usaybia` do that (and should it be `https://srophe.app/usaybia` instead)? 

**Versioning:** I want (and need) to be able to assign version numbers to Usaybia-specific developments. I'm not sure how to do that _and also_ show what version of the Srophé base its on. 

In the future would [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) perhaps be a way to address core vs. project-specific code versioning in a transparent way?

**Comment by nathangibson** [comment]
I bring this up because if we're going to change the version numbering system for Usaybia, the new repo is a good time to do it. Otherwise I can just go with 0.9.0 since the other repo went through 0.8.0.

**Comment by wsalesky** [comment]
You can carry on with your versioning. I will try to be better about doing releases for the Srophe application, that might make it easier to keep track of what version you are on. I suppose we can add a srophe app version number to the repo-config.xml file as well if that helps keep track of things.

**Comment by nathangibson** [comment]
OK great. I would love to have more clarity on upstream changes but Srophé is your baby so you should get to decide what that looks like :-). You can just let me know what I should add to the repo-config or do a PR.

**Comment by wsalesky** [comment]
@nathangibson Sorry, I know it has been a bit of a mess, if you have suggestions I'm happy to adjust. I will try to start making changes to Srophe as more managed releases for new features.

**Comment by nathangibson** [comment]
@wsalesky That's ok. Releases with version numbers would be great. I've taken a look, and if you do Github "releases," it is possible to then do a downstream PR from the release version tag. For example, if there is a v1.1 at srophe/srophe, we can do a PR to merge this specific release into srophe/usaybia. I think that would make the process of adopting upstream changes more transparent. 

For the longer-term: what I've seen with submodules is the possibility of essentially including versioned "libraries" so that the library code doesn't have to be managed in the repo using it. I don't know if it would be possible to have something like a "srophe core" with project-specific implementations sitting outside this, but submoduling might be possible in that kind of scenario.
