### ISSUE TITLE
Aristotle https://usaybia.net/person/565 doesn't appear in search results

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe#12]
@wsalesky (cc: @Uggifletzet ) Can you see any reason why Aristotle https://usaybia.net/person/565 doesn't appear in search results for https://usaybia.net/search.html?keyword=Aristotle ?

**Comment by wsalesky** [comment]
@nathangibson This looks like an app bug. I'm going to link to it on they srophe app and fix there, then we can patch here with the update.

**Comment by nathangibson** [comment]
Thanks!
