### ISSUE TITLE
Search for https://usaybia.net/search.html?keyword=ridwan returns 503

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe#14]
@wsalesky Not sure what's going on here, other searches seem to be fine. I get a 503 for this specific search https://usaybia.net/search.html?keyword=ridwan. Maybe something wrong in the data?

**Comment by wsalesky** [comment]
This search works for me.  Perhaps you just need a hard refresh?  

<img width="1265" alt="Screenshot 2023-02-02 at 7 22 03 AM" src="https://user-images.githubusercontent.com/1168206/216323546-96fefb25-469a-4acb-a0fc-fd04f577cbf8.png">

**Comment by nathangibson** [comment]
Thanks, works now, not sure what was happening!
