### ISSUE TITLE
Missing browse customizations

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe#8]
@wsalesky Regarding browse features:

~~- [ ] Previously we had Browse for persons (maybe for everything) going directly to Advanced browse. This is now gone.~~
- [ ] Even with reindexing I don't see Occupation facets for persons advanced browse.

#1
<img width="1233" alt="Screen Shot 2022-05-16 at 16 10 14" src="https://user-images.githubusercontent.com/3083452/168617242-6f3cc15c-1c92-4a8e-b91c-cb555d01e852.png">

**Comment by nathangibson** [comment]
@wsalesky The first was just my faulty memory.

**Comment by wsalesky** [comment]
@nathangibson Do you want it on all the browse options, or do you want it in only the advanced browse?

**Comment by nathangibson** [comment]
Just advanced browse. Eventually I would like to make the advanced browse/faceted view the default but we can get there one step at a time.

**Comment by wsalesky** [comment]
fixed

**Comment by nathangibson** [comment]
@wsalesky Great, thx, testing ...

**Comment by nathangibson** [comment]
Looks good!
